# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: g:/Git/fpgaLearning/Neptune/vivado2018/INTR_SD/INTR_SD/INTR_SD.srcs/sources_1/bd/intr_sd/ip/intr_sd_processing_system7_0_0/intr_sd_processing_system7_0_0.xci
# IP: The module: 'intr_sd_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: g:/Git/fpgaLearning/Neptune/vivado2018/INTR_SD/INTR_SD/INTR_SD.srcs/sources_1/bd/intr_sd/ip/intr_sd_processing_system7_0_0/intr_sd_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'intr_sd_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: g:/Git/fpgaLearning/Neptune/vivado2018/INTR_SD/INTR_SD/INTR_SD.srcs/sources_1/bd/intr_sd/ip/intr_sd_processing_system7_0_0/intr_sd_processing_system7_0_0.xci
# IP: The module: 'intr_sd_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: g:/Git/fpgaLearning/Neptune/vivado2018/INTR_SD/INTR_SD/INTR_SD.srcs/sources_1/bd/intr_sd/ip/intr_sd_processing_system7_0_0/intr_sd_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'intr_sd_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
