# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: g:/Git/fpgaLearning/YeHuo/vivado2018/led_zynq/led_ip_pl/led_ip_pl.srcs/sources_1/bd/led_ip_design/ip/led_ip_design_auto_pc_0/led_ip_design_auto_pc_0.xci
# IP: The module: 'led_ip_design_auto_pc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: g:/Git/fpgaLearning/YeHuo/vivado2018/led_zynq/led_ip_pl/led_ip_pl.srcs/sources_1/bd/led_ip_design/ip/led_ip_design_auto_pc_0/led_ip_design_auto_pc_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'led_ip_design_auto_pc_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: g:/Git/fpgaLearning/YeHuo/vivado2018/led_zynq/led_ip_pl/led_ip_pl.srcs/sources_1/bd/led_ip_design/ip/led_ip_design_auto_pc_0/led_ip_design_auto_pc_0.xci
# IP: The module: 'led_ip_design_auto_pc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: g:/Git/fpgaLearning/YeHuo/vivado2018/led_zynq/led_ip_pl/led_ip_pl.srcs/sources_1/bd/led_ip_design/ip/led_ip_design_auto_pc_0/led_ip_design_auto_pc_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'led_ip_design_auto_pc_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
