set_property SRC_FILE_INFO {cfile:G:/Git/fpgaLearning/YeHuo/vivado2018/SD/SD_multi_GPIO/multi_GPIO.srcs/constrs_1/new/multi_GPIO.xdc rfile:../../../multi_GPIO.srcs/constrs_1/new/multi_GPIO.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN G20 [get_ports {GPIO_0_0_tri_io[0]}]
set_property src_info {type:XDC file:1 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN K16 [get_ports {GPIO_0_0_tri_io[1]}]
set_property src_info {type:XDC file:1 line:5 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN H15 [get_ports {gpio_rtl_0_tri_io[0]}]
