# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/mio_psled_design/mio_psled_design.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mio_psled_design || ORIG_REF_NAME==mio_psled_design} -quiet] -quiet

# IP: bd/mio_psled_design/ip/mio_psled_design_processing_system7_0_0/mio_psled_design_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mio_psled_design_processing_system7_0_0 || ORIG_REF_NAME==mio_psled_design_processing_system7_0_0} -quiet] -quiet

# XDC: bd/mio_psled_design/mio_psled_design_ooc.xdc
