# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/emio_io.xdc

# Block Designs: bd/emio_design/emio_design.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==emio_design || ORIG_REF_NAME==emio_design} -quiet] -quiet

# IP: bd/emio_design/ip/emio_design_processing_system7_0_0/emio_design_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==emio_design_processing_system7_0_0 || ORIG_REF_NAME==emio_design_processing_system7_0_0} -quiet] -quiet

# XDC: bd/emio_design/emio_design_ooc.xdc
