set_property SRC_FILE_INFO {cfile:G:/Git/fpgaLearning/YeHuo/vivado2018/emio/emio/emio.srcs/constrs_1/new/emio_io.xdc rfile:../../../emio.srcs/constrs_1/new/emio_io.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN G20 [get_ports {GPIO_EMIO_tri_io[0]}]
set_property src_info {type:XDC file:1 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN K16 [get_ports {GPIO_EMIO_tri_io[1]}]
