# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/intr_sd/intr_sd.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==intr_sd || ORIG_REF_NAME==intr_sd} -quiet] -quiet

# IP: bd/intr_sd/ip/intr_sd_processing_system7_0_0/intr_sd_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==intr_sd_processing_system7_0_0 || ORIG_REF_NAME==intr_sd_processing_system7_0_0} -quiet] -quiet

# XDC: bd/intr_sd/intr_sd_ooc.xdc
