# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/mio_design/mio_design.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mio_design || ORIG_REF_NAME==mio_design} -quiet] -quiet

# IP: bd/mio_design/ip/mio_design_processing_system7_0_0/mio_design_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mio_design_processing_system7_0_0 || ORIG_REF_NAME==mio_design_processing_system7_0_0} -quiet] -quiet

# XDC: bd/mio_design/mio_design_ooc.xdc
