# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/led_ip_hw.xdc

# Block Designs: bd/led_ip_design/led_ip_design.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==led_ip_design || ORIG_REF_NAME==led_ip_design} -quiet] -quiet

# IP: bd/led_ip_design/ip/led_ip_design_processing_system7_0_0/led_ip_design_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==led_ip_design_processing_system7_0_0 || ORIG_REF_NAME==led_ip_design_processing_system7_0_0} -quiet] -quiet

# IP: bd/led_ip_design/ip/led_ip_design_led_ip_0_0/led_ip_design_led_ip_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==led_ip_design_led_ip_0_0 || ORIG_REF_NAME==led_ip_design_led_ip_0_0} -quiet] -quiet

# IP: bd/led_ip_design/ip/led_ip_design_auto_pc_0/led_ip_design_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==led_ip_design_auto_pc_0 || ORIG_REF_NAME==led_ip_design_auto_pc_0} -quiet] -quiet

# IP: bd/led_ip_design/ip/led_ip_design_ps7_0_axi_periph_0/led_ip_design_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==led_ip_design_ps7_0_axi_periph_0 || ORIG_REF_NAME==led_ip_design_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/led_ip_design/ip/led_ip_design_rst_ps7_0_50M_0/led_ip_design_rst_ps7_0_50M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==led_ip_design_rst_ps7_0_50M_0 || ORIG_REF_NAME==led_ip_design_rst_ps7_0_50M_0} -quiet] -quiet

# XDC: bd/led_ip_design/led_ip_design_ooc.xdc
